export const SEARCH_EMPLOYEE='SEARCH_EMPLOYEE'
export const EMPLOYEE_DATA_REQUEST='EMPLOYEE_DATA_REQUEST'
export const EMPLOYEE_DATA_SUCCESS='EMPLOYEE_DATA_SUCCESS'
export const EMPLOYEE_DATA_FAIL='EMPLOYEE_DATA_FAIL'
export const ADD_EMPLOYEE_REQUEST='ADD_EMPLOYEE_REQUEST'
export const ADD_EMPLOYEE_SUCCESS='ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_FAIL='ADD_EMPLOYEE_FAIL'




